[package]
name = "my_bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linuxkeys = { path = "../" }
xdotool = "0.0.2"